name: Cucumber Tests

on: push

jobs:
  build:
    name: Cucumner runer
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean verify

      - name: Run Cucumber Tests
        run: mvn test